name: nickel
channels:
  - defaults
dependencies:
  - python>=3.11
  - pip>=22.3.1
  - matplotlib>=3.6.3
  - numpy>=1.23.5
  - jupyterlab
  - pip:
    - qiskit[visualization]>=1.0
    - qiskit-aer>=0.14.0.1
    - qutip>=4.7.3
    - cirq>=1.4.0
    - pylatexenc